export const farmer = {
  name: 'Ramu Rao',
  nameTE: 'రాము రావు',
  phone: '+91 94012 34567',
  village: 'Pedakurapadu',
  district: 'Guntur',
  state: 'Andhra Pradesh',
  fpo: 'Guntur Rythu Mitra FPO',
  memberSince: 'March 2024',
  totalSales: 4,
}

export const produce = {
  id: 'LOT-2026-091',
  crop: 'Tomatoes',
  cropTE: 'టమోటాలు',
  variety: 'Hybrid Roma',
  quantity: 1000,
  harvestDays: 2,
  harvestDate: 'Sep 6, 2026',
  location: 'Pedakurapadu, Guntur',
  quality: 'Grade A',
  coldStorage: false,
  cashUrgency: 'high' as const,
  photo: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&h=400&fit=crop&auto=format',
  spoilageRisk: 'high' as const,
  spoilageReason: 'No cold storage · Harvested in 2 days',
}

export const markets = [
  {
    id: 1,
    name: 'Guntur APMC Mandi',
    type: 'mandi' as const,
    price: 22,
    minPrice: 18,
    maxPrice: 24,
    modalPrice: 22,
    distance: 8,
    demand: 'Medium' as const,
    trend: 'declining' as const,
    arrivals: 'High',
    verified: false,
    rating: null as null | number,
    payment: '1–2 days',
    pickup: 'Today',
  },
  {
    id: 2,
    name: 'ABC Foods Pvt Ltd',
    type: 'buyer' as const,
    price: 24,
    minPrice: 24,
    maxPrice: 24,
    modalPrice: 24,
    distance: 18,
    demand: 'High' as const,
    trend: 'stable' as const,
    arrivals: 'N/A',
    verified: true,
    rating: 4.7,
    payment: 'Within 24 hours',
    pickup: 'Tomorrow 8 AM',
  },
  {
    id: 3,
    name: 'Vijayawada APMC',
    type: 'mandi' as const,
    price: 25,
    minPrice: 22,
    maxPrice: 27,
    modalPrice: 25,
    distance: 30,
    demand: 'High' as const,
    trend: 'stable' as const,
    arrivals: 'Medium',
    verified: false,
    rating: null as null | number,
    payment: '2–3 days',
    pickup: 'Day after tomorrow',
  },
]

export const recommendations = [
  {
    rank: 1,
    marketId: 2,
    name: 'ABC Foods Pvt Ltd',
    price: 24,
    grossRevenue: 24000,
    transport: -1000,
    loading: -200,
    fees: 0,
    spoilage: 0,
    netEarnings: 22800,
    distance: 18,
    pickup: 'Tomorrow 8 AM',
    verified: true,
    rating: 4.7,
    reason: 'Good price + nearby pickup + verified buyer + lower transport cost. Quickest payment.',
    paymentTerms: 'Within 24 hours',
    highlight: true,
  },
  {
    rank: 2,
    marketId: 3,
    name: 'Vijayawada APMC',
    price: 25,
    grossRevenue: 25000,
    transport: -2500,
    loading: -300,
    fees: -250,
    spoilage: -500,
    netEarnings: 21450,
    distance: 30,
    pickup: 'Day after tomorrow',
    verified: false,
    rating: null as null | number,
    reason: 'Higher headline price but 30 km away. Extra transport and 2-day delay increases spoilage risk.',
    paymentTerms: '2–3 days',
    highlight: false,
  },
  {
    rank: 3,
    marketId: 1,
    name: 'Guntur APMC Mandi',
    price: 22,
    grossRevenue: 22000,
    transport: -600,
    loading: -200,
    fees: -220,
    spoilage: -300,
    netEarnings: 20680,
    distance: 8,
    pickup: 'Today',
    verified: false,
    rating: null as null | number,
    reason: 'Closest option but price is declining. High arrivals from nearby farmers. Only if you need cash today.',
    paymentTerms: 'Same day',
    highlight: false,
  },
]

export const buyers = [
  {
    id: 1,
    name: 'ABC Foods Pvt Ltd',
    verified: true,
    rating: 4.7,
    reviews: 142,
    needs: '800–5,000 kg tomatoes',
    qualityReq: 'Grade A or B',
    price: 24,
    pickup: 'Tomorrow 8 AM',
    payment: 'Within 24 hours',
    distance: 18,
    netEarnings: 22800,
    contact: '+91 98765 43210',
    location: 'Narasaraopet, Guntur',
  },
  {
    id: 2,
    name: 'FreshLink Traders',
    verified: true,
    rating: 4.2,
    reviews: 67,
    needs: '500–2,000 kg tomatoes',
    qualityReq: 'Grade A',
    price: 23,
    pickup: 'Day after tomorrow',
    payment: 'Within 48 hours',
    distance: 22,
    netEarnings: 21100,
    contact: '+91 94823 11234',
    location: 'Mangalagiri, Guntur',
  },
  {
    id: 3,
    name: 'Green Valley Exports',
    verified: false,
    rating: 3.9,
    reviews: 28,
    needs: '2,000–10,000 kg tomatoes',
    qualityReq: 'Grade A',
    price: 23.5,
    pickup: 'In 3 days',
    payment: '3–5 days',
    distance: 40,
    netEarnings: 20900,
    contact: '+91 90000 55555',
    location: 'Guntur City',
  },
]

export const transportOptions = [
  {
    id: 1,
    type: 'Mini Truck',
    capacity: '1.5 ton',
    cost: 1000,
    costPerKg: 1.0,
    pickup: 'Tomorrow 7 AM',
    provider: 'Ravi Transport',
    phone: '+91 99011 22334',
  },
  {
    id: 2,
    type: 'Tata Ace',
    capacity: '750 kg',
    cost: 700,
    costPerKg: 1.4,
    pickup: 'Tomorrow 6 AM',
    provider: 'Suresh Vehicles',
    phone: '+91 98452 67890',
    note: 'Requires 2 trips for 1,000 kg',
  },
  {
    id: 3,
    type: 'Shared Truck (FPO)',
    capacity: '5 ton shared',
    cost: 500,
    costPerKg: 0.5,
    pickup: 'Tomorrow 9 AM',
    provider: 'Kisan Logistics FPO',
    phone: '+91 97890 11111',
    note: 'FPO member benefit — discounted rate',
  },
]

export const orderStatus = {
  id: 'ORD-2026-0912',
  buyer: 'ABC Foods Pvt Ltd',
  crop: 'Tomatoes',
  quantity: 1000,
  price: 24,
  total: 24000,
  netEarnings: 22800,
  pickupDate: 'Sep 7, 2026 at 8 AM',
  driver: 'Srinivas Rao',
  driverPhone: '+91 97001 23456',
  vehicle: 'AP 16 AB 4567',
  steps: [
    { label: 'Order Confirmed', done: true, time: 'Sep 5, 3:12 PM' },
    { label: 'Vehicle Assigned', done: true, time: 'Sep 5, 4:30 PM' },
    { label: 'Pickup', done: false, time: 'Sep 7, 8:00 AM' },
    { label: 'In Transit', done: false, time: '' },
    { label: 'Delivered', done: false, time: '' },
    { label: 'Payment', done: false, time: '' },
  ],
}

export const payment = {
  orderId: 'ORD-2026-0912',
  buyer: 'ABC Foods Pvt Ltd',
  crop: 'Tomatoes',
  quantity: 1000,
  agreedPrice: 24,
  grossAmount: 24000,
  deductions: [
    { label: 'Transport (Mini Truck)', amount: -1000 },
    { label: 'Loading & Handling', amount: -200 },
    { label: 'Platform Fee', amount: 0 },
  ],
  netAmount: 22800,
  status: 'pending' as 'pending' | 'processing' | 'paid',
  expectedDate: 'Sep 8, 2026',
  paymentMode: 'UPI / Bank Transfer',
  upiId: 'ramurao@upi',
}

export const alerts = [
  {
    id: 1,
    icon: '🍅',
    text: 'Tomato price increased by ₹2/kg in Vijayawada APMC.',
    time: '10 min ago',
    type: 'price',
  },
  {
    id: 2,
    icon: '🚚',
    text: 'ABC Foods pickup confirmed for tomorrow 8 AM.',
    time: '1 hr ago',
    type: 'pickup',
  },
  {
    id: 3,
    icon: '⚠️',
    text: 'Spoilage risk is increasing. Consider selling within 24 hours.',
    time: '2 hrs ago',
    type: 'risk',
  },
  {
    id: 4,
    icon: '🤝',
    text: 'FPO bulk lot opportunity: 12,000 kg tomatoes at ₹23/kg.',
    time: '3 hrs ago',
    type: 'fpo',
  },
]

export const salesHistory = [
  { month: 'Jul 2026', crop: 'Chillies', qty: 800, gross: 22400, transport: 1600, loading: 240, fees: 0, net: 20560, status: 'Paid' },
  { month: 'May 2026', crop: 'Onion', qty: 1200, gross: 18000, transport: 1200, loading: 360, fees: 180, net: 16260, status: 'Paid' },
  { month: 'Mar 2026', crop: 'Tomatoes', qty: 600, gross: 14400, transport: 720, loading: 180, fees: 144, net: 13356, status: 'Paid' },
  { month: 'Jan 2026', crop: 'Potato', qty: 900, gross: 15300, transport: 900, loading: 270, fees: 153, net: 13977, status: 'Paid' },
]

export const profitSummary = {
  season: 'Kharif 2026',
  totalSales: 4,
  totalQuantity: 3500,
  totalGross: 70100,
  totalTransport: 4420,
  totalLoading: 1050,
  totalFees: 477,
  totalSpoilage: 0,
  totalNet: 64153,
  avgPricePerKg: 18.3,
  mandiAvgPerKg: 15.9,
}

export const priceTrend = [
  { day: 'Mon', price: 26, predicted: false },
  { day: 'Tue', price: 25, predicted: false },
  { day: 'Wed', price: 24, predicted: false },
  { day: 'Thu', price: 23, predicted: true },
  { day: 'Fri', price: 21, predicted: true },
]

export const buyerListings = [
  {
    id: 'L001',
    farmerName: 'Ramu Rao',
    farmerVerified: true,
    location: 'Pedakurapadu, Guntur',
    crop: 'Tomatoes',
    variety: 'Hybrid Roma',
    quantity: 1000,
    quality: 'Grade A',
    askedPrice: 22,
    harvestDate: 'Sep 6, 2026',
    photo: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400&h=300&fit=crop&auto=format',
    spoilageRisk: 'high',
    bidsCount: 2,
  },
  {
    id: 'L002',
    farmerName: 'Suresh Kumar',
    farmerVerified: true,
    location: 'Narasaraopet, Guntur',
    crop: 'Tomatoes',
    variety: 'Deshi',
    quantity: 800,
    quality: 'Grade B',
    askedPrice: 20,
    harvestDate: 'Sep 8, 2026',
    photo: 'https://images.unsplash.com/photo-1558818498-28c1e002b655?w=400&h=300&fit=crop&auto=format',
    spoilageRisk: 'medium',
    bidsCount: 1,
  },
  {
    id: 'L003',
    farmerName: 'Laxmi Devi',
    farmerVerified: false,
    location: 'Tenali, Guntur',
    crop: 'Chillies',
    variety: 'Guntur Red',
    quantity: 500,
    quality: 'Grade A',
    askedPrice: 95,
    harvestDate: 'Sep 10, 2026',
    photo: 'https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=400&h=300&fit=crop&auto=format',
    spoilageRisk: 'low',
    bidsCount: 3,
  },
]

export const fpoMembers = [
  { id: 1, name: 'Ramu Rao', village: 'Pedakurapadu', crop: 'Tomatoes', qty: 1000, status: 'Ready', net: 22800 },
  { id: 2, name: 'Suresh Kumar', village: 'Narasaraopet', crop: 'Tomatoes', qty: 800, status: 'Harvested', net: 18240 },
  { id: 3, name: 'Venkat Rao', village: 'Mangalagiri', crop: 'Tomatoes', qty: 1200, status: 'Ready', net: 27360 },
  { id: 4, name: 'Krishnaiah', village: 'Chilakaluripet', crop: 'Tomatoes', qty: 600, status: 'Pending', net: 13680 },
  { id: 5, name: 'Laxmi Devi', village: 'Tenali', crop: 'Chillies', qty: 500, status: 'Ready', net: 47500 },
]

export const fpoSummary = {
  name: 'Guntur Rythu Mitra FPO',
  members: 47,
  activeLots: 8,
  totalQty: 28400,
  bulkTargetPrice: 23,
  estimatedBulkNet: 642000,
}

export const pricePredictions = {
  currentPerQtl: 2400,
  tomorrowPerQtl: 2450,
  threeDaysPerQtl: 2600,
  sevenDaysPerQtl: 2520,
  currentPerKg: 24,
  tomorrowPerKg: 24.5,
  threeDaysPerKg: 26,
  sevenDaysPerKg: 25.2,
  confidence: 78,
  trend: 'rises then falls' as const,
  trendBars: [
    { label: 'Today', price: 24, predicted: false },
    { label: 'Mon', price: 24.5, predicted: true },
    { label: 'Wed', price: 26, predicted: true },
    { label: 'Fri', price: 25.2, predicted: true },
  ],
}

export const spoilageData = {
  riskLevel: 'HIGH' as const,
  riskScore: 78,
  safeWindow: '2–3 days',
  valueLossAfterDeadline: 15,
  deadline: 'Sell within 2 days',
  storageTip: 'Keep in shade, avoid direct sunlight and moisture',
  shelfLifeDays: 3,
  potentialLoss: 1500,
}

export const qualityData = {
  score: 82,
  grade: 'A',
  overall: 'Good',
  marketValueRange: '₹2,300–₹2,500',
  marketValuePerKg: '₹23–₹25',
  indicators: [
    { label: 'Fresh appearance', ok: true },
    { label: 'Good colour', ok: true },
    { label: 'Good size & uniformity', ok: true },
    { label: 'Minor surface damage', ok: false },
    { label: 'Slight signs of aging', ok: false },
  ],
  suggestedAction: 'Good time to sell',
  disclaimer: 'AI quality assessment is based on the uploaded image. For accurate grading, physical inspection may be required.',
}

export const negotiationMessages = [
  { from: 'buyer' as const, text: 'We offer ₹24/kg for 1,000 kg. Payment within 24 hours. Pickup tomorrow morning.', time: '3:10 PM' },
  { from: 'farmer' as const, text: 'Grade A Hybrid Roma. Looking for ₹25/kg.', time: '3:18 PM' },
  { from: 'buyer' as const, text: 'Best we can do is ₹24.50/kg. Final offer.', time: '3:35 PM' },
]

export const qcData = {
  agreedQty: 1000,
  actualQty: 980,
  agreedQuality: 'Grade A',
  actualQuality: 'Grade A',
  pricePerKg: 24,
  buyerNotes: 'Minor transit weight loss (20 kg). Quality confirmed Grade A.',
  grossAgreed: 24000,
  grossActual: 23520,
  transport: 1000,
  loading: 200,
  netFinal: 22320,
}

export const buyerProfile = {
  id: 1,
  name: 'ABC Foods Pvt Ltd',
  verified: true,
  rating: 4.7,
  reviews: 142,
  completedDeals: 142,
  paymentReliability: 99,
  pickupReliability: 97,
  location: 'Narasaraopet, Guntur',
  distance: 18,
  about: 'Established tomato processor supplying to Hyderabad & Bengaluru markets. Grade A-only buyer with doorstep pickup.',
  currentOffer: 24,
  recentReviews: [
    { farmer: 'Venkat Rao', village: 'Mangalagiri', rating: 5, text: 'Payment same day. Very professional. Will sell again.', date: 'Aug 2026' },
    { farmer: 'Suresh Kumar', village: 'Narasaraopet', rating: 5, text: 'Good price, on-time pickup. Highly recommend.', date: 'Jul 2026' },
    { farmer: 'Krishnaiah', village: 'Chilakaluripet', rating: 4, text: 'Payment in 24 hrs as promised. Pickup was 30 min late.', date: 'Jun 2026' },
  ],
}
